"""
Django settings for pharmacydb project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import dotenv_values


def split_env(env, delimiter=','):
    return env.split(delimiter) if env else []


BASE_DIR = Path(__file__).resolve().parent.parent

envs = {
    'CI': 'ci',
    'DEV': 'development',
    'PROD': 'production',
}

CI = os.getenv('GITHUB_WORKFLOW')
ENVIRONMENT = envs['CI'] if CI else os.getenv('ENVIRONMENT', envs['DEV'])

config = (
    {
        **dotenv_values(".env.dev"),  # allowed in version control
        **dotenv_values(".env.dev-secret"),  # not allowed in version control
        **os.environ,
    }
    if ENVIRONMENT == envs['DEV']
    else os.environ
)

SECRET_KEY = config.get('SECRET_KEY')
if not SECRET_KEY and ENVIRONMENT in [envs['DEV'], envs['CI']]:
    # NOT FOR PRODUCTION USE
    SECRET_KEY = ("One sometimes finds what one is not looking for")

DEBUG = config.get('DEBUG') == 'True'

ALLOWED_HOSTS = split_env(config.get('ALLOWED_HOSTS'))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pharmacy",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pharmacydb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pharmacydb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR.parent / "PharmacyDB.db",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_SUPERUSER_EMAIL = config.get('AUTH_SUPERUSER_EMAIL')
AUTH_SUPERUSER_PASSWORD = config.get('AUTH_SUPERUSER_PASSWORD')

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
